---
   - name: Ensure old versions of Docker are not installed.
     yum:
       name: "{{ old_redhat_packages }}"
       state: absent
   - name: Install yum utils   
     yum:
       name: "{{ yum_utils }}"
       state: latest 
       update_cache: yes
   - name: Add Docker GPG key.
     rpm_key:
       key: "{{ docker_yum_gpg_key }}"
       state: present
   - name: Add Docker repo - redhat
     get_url:
        url: "{{ redhat_repository }}"
        dest: "{{ redhat_repository_dest }}"
        mode: 0644
   - name: Enable Docker Edge repo
     ini_file:
        dest: "{{ Docker_Edge_repo }}"
        section: 'docker-ce-edge'
        option: enabled
        value: '0'
   - name: Enable Docker Test repo
     ini_file:
        dest: "{{ Docker_Test_repo }}"
        section: 'docker-ce-test'
        option: enabled
        value: '0'
   - name: Install Docker packages
     yum:
      name: "{{ docker_packages }}"
      state: latest
      update_cache: yes
     notify: restart docker
   - name: Install Docker Module for Python
     pip:
      name: docker
   - name: add users to docker group
     user:
      name: "{{ user_redhat }}"
      groups: docker
      append: yes

      